theme: jekyll-theme-minimal
title: [GE High Assurance]
description: [The GE High Assurance Systems research team is devoted to developing technology and tools to support trust in software intensive critical infrastructure.]
